logging:
  level:
    sql: info
    net.thumbtack: DEBUG
    org.springframework: INFO
    org.hibernate: DEBUG
    com.aerospike: DEBUG

spring:
  main:
    banner-mode: off
  jpa:
    show-sql: true
  flyway:
    enabled=true:


db:
  name: ptpb
  port: 3000
  host: localhost
