server:
  port: 8090
spring:
  main:
    banner-mode: off
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: test

db:
  namespace: ptpb
  port: 3000
  host: localhost
