version: "3.0"

services:
    ptpb_jenkins:
        build:
          context: .
          dockerfile: ./jenkins/Dockerfile
        restart: always
        ports:
          - 49001:8080
          - 50000:50000
        privileged: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ../data/jenkins:/var/jenkins_home
          - /usr/bin/docker:/usr/bin/docker

    ptpb_rabbit:
        image: rabbitmq:3-management
        hostname: rabbit
        ports:
          - 5672:5672
          - 15672:15672
        volumes:
          - ../data/rabbitmq:/var/lib/rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=test
          - RABBITMQ_DEFAULT_PASS=test

    ptpb_aerospike:
        image: aerospike:latest
        ports:
          - 3000:3000
          - 3001:3001
          - 3002:3002
          - 3003:3003
        volumes:
          - ../data/aerospike/etc:/opt/aerospike/etc
          - ../data/aerospike/data:/opt/aerospike/data
        command: [asd, --config-file, /opt/aerospike/etc/aerospike.conf]



