version: "3.0"

services:
    ptpb_jenkins:
        build:
          context: .
          dockerfile: ./jenkins/Dockerfile
        restart: always
        ports:
          - 49001:8080
          - 50000:50000
        privileged: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ../data/jenkins:/var/jenkins_home
          - /usr/bin/docker:/usr/bin/docker
